-- Migration: Fix courses table unique constraint
-- ================================================
-- From: UNIQUE on course_code (global)
-- To: UNIQUE on (course_code, semester, department_id) composite
--
-- This allows the same course code to exist in different departments
-- while maintaining uniqueness for each department+semester combination.
--
-- ISSUE RESOLVED:
-- Hibernate's ddl-auto=update creates new constraints but doesn't drop old ones.
-- This caused both old (global) and new (composite) constraints to exist,
-- leading to duplicate key errors like: "Duplicate entry 'AD231C1' for key 'UK_p02ts69sh53ptd62m3c67v0'"
--
-- SOLUTION:
-- 1. Drop old global constraint (named by Hibernate: UK_p02ts69sh53ptd62m3c67v0 or similar)
-- 2. Keep only the composite constraint (Hibernate generated: UK9bw4dns6cq6r39s51f6bhrn8r or similar)
-- 3. Clear courses table for clean import test

-- Step 1: Drop the old global unique constraint
-- The exact constraint name is generated by Hibernate
ALTER TABLE courses DROP INDEX IF EXISTS UK_p02ts69sh53ptd62m3c67v0;

-- Fallback: If constraint has different name, try generic "course_code" name
-- ALTER TABLE courses DROP INDEX IF EXISTS course_code;

-- Step 2: Verify composite constraint exists
-- SELECT CONSTRAINT_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
-- WHERE TABLE_NAME = 'courses' AND CONSTRAINT_NAME NOT IN ('PRIMARY', 'FK%');

-- Step 3: Optional - Clear courses table for fresh import test
-- DELETE FROM courses;

-- Verification:
-- SHOW KEYS FROM courses WHERE Key_name NOT IN ('PRIMARY', 'FK%');
